POST http://localhost:3333/tasks
Content-Type: application/json

{
    "title": "achar loja de mochila personalizada",
    "description": "",
    "parentId": "b89be282-fceb-45da-bf9a-2158081cd624"
}

###
//get all tasks and divide by subtasks
GET http://localhost:3333/tasks?page=0&max_depth=2
Content-Type: application/json

###
//get an especific task
GET http://localhost:3333/tasks/145972c3-9a61-409b-85f8-35002039f074

###
// complete an task and their subtasks
POST http://localhost:3333/task/645e5f24-6990-4ea7-97e6-b02f395ddaa9/complete