### Create a project.
POST http://localhost:3333/project
content-type: application/json

{
    "name":"House-keeper2",
    "description":"um projeto de automação residencial e IoT."
}

### Create a task with or without parentId but passing project ID.
POST http://localhost:3333/project/7a62f62a-0e20-4bcf-a7a7-6b9476a29425/tasks
Content-Type: application/json

{
    "title":"Arrumar o link para o site das bolsas",
    "description":"coloquei o site de porno gay furry sem querer",
    "parentId": "887e8d36-393e-41c1-b241-c62d3eb66008"
}

### Gets all tasks from a project passing the project ID.
GET  http://localhost:3333/project/7a62f62a-0e20-4bcf-a7a7-6b9476a29425/tasks
Content-Type: application/json


### Get a specific task with its subtasks
GET http://localhost:3333/tasks/887e8d36-393e-41c1-b241-c62d3eb66008
Content-Type: application/json

### Toggle specific task completion with its subtasks
PUT http://localhost:3333/tasks/5b60e461-8a57-4919-8c11-54bf275646b4/complete
Content-Type: application/json

{
    "isCompleted":true
}


### UpdateTask info
PATCH  http://localhost:3333/tasks/5df25fde-ca43-49df-a3ae-d6a0043f7fba
Content-Type: application/json

{
    "parentId": null
}

### delete a task and its subtasks
DELETE http://localhost:3333/tasks/5df25fde-ca43-49df-a3ae-d6a0043f7fba


### registers a new user
POST http://localhost:3333/auth/register
Content-Type: application/json

{
    "userName": "retr0lbb",
    "email": "retr0lbb@gmail.com",
    "password": "123123"
}